//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Architecture for Swift
//

import Foundation


protocol ___FILEBASENAMEASIDENTIFIER___PresenterDelegate : class {
    
    func successFetch___FILEBASENAMEASIDENTIFIER___(___FILEBASENAMEASIDENTIFIER___s : AnyObject)
    func failureFetch___FILEBASENAMEASIDENTIFIER___(___FILEBASENAMEASIDENTIFIER___s : ErrorType)
    
}

public struct ___FILEBASENAMEASIDENTIFIER___Presenter {
    
    // Use Case
    var service : ___FILEBASENAMEASIDENTIFIER___Service!
    private weak var delegate : ___FILEBASENAMEASIDENTIFIER___PresenterDelegate!
    
    init(service: ___FILEBASENAMEASIDENTIFIER___Service, delegate: ___FILEBASENAMEASIDENTIFIER___PresenterDelegate) {
        self.service = service
        self.delegate = delegate
    }
    
}


extension ___FILEBASENAMEASIDENTIFIER___Presenter {
    // write your function here !
}
