//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Architecture for Swift
//


import UIKit


class ___FILEBASENAMEASIDENTIFIER___ViewController: UICollectionViewController {
    
    
    
    lazy var presenter : ___FILEBASENAMEASIDENTIFIER___Presenter = {
        #if MOCK
            print("MOCK BUILD")
            let repo = Mock___FILEBASENAMEASIDENTIFIER___RepositoryImp()
        #elseif DEV
            print("DEV BUILD")
            // it might be local data base implementation or wherever ..
            let repo = Sandbox___FILEBASENAMEASIDENTIFIER___RepositoryImp()
        #elseif PRODUCTION
            print("PRODUCTION BUILD")
            let repo = Network___FILEBASENAMEASIDENTIFIER___RepositoryImp()
        #endif
        
        let service = ___FILEBASENAMEASIDENTIFIER___Service(repo: repo)
        return ___FILEBASENAMEASIDENTIFIER___Presenter(service: service, delegate: self)
    }()

    // MARK: View Lifecycle
    override func viewDidLoad() {
        super.viewDidLoad()
        
    }
}
