//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Architecture for Swift
//


import Foundation

// Use Case
public struct ___FILEBASENAMEASIDENTIFIER___Service : UseCase {
    
    var repo : ___FILEBASENAMEASIDENTIFIER___Repository!
    public func execute(request : UseCaseRequest ) -> <#element | elements #> {
        return repo.<#Function Name#>
    }
    
    init(repo : ___FILEBASENAMEASIDENTIFIER___Repository) {
        self.repo = repo
    }
    
}
